#############################################################################
# Makefile for building: qt_simul
# Generated by qmake (2.01a) (Qt 4.7.4) on: Wed Aug 21 17:03:05 2013
# Project:  qt_simul.pro
# Template: app
# Command: /usr/local/Qt.4.7-static/bin/qmake -spec /usr/local/Qt.4.7-static/mkspecs/linux-g++ CONFIG+=debug -o Makefile qt_simul.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_TTY_POSIX_ -DQT_SQL_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Qt.4.7-static/mkspecs/linux-g++ -I. -I/usr/local/Qt.4.7-static/include/QtCore -I/usr/local/Qt.4.7-static/include/QtNetwork -I/usr/local/Qt.4.7-static/include/QtGui -I/usr/local/Qt.4.7-static/include/QtOpenGL -I/usr/local/Qt.4.7-static/include/QtSql -I/usr/local/Qt.4.7-static/include -I./usr/include/GL -Ilibku/libmodbus -Ilibku/libmodbus/src -Ilibku/qextserialport-1.2beta2/src -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Qt.4.7-static/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Qt.4.7-static/lib -L/usr/X11R6/lib -lc -lgcc -lglut -lGLC -L./libku/libmodbus/src -L/home/iqbal/suralaya/master/libku/qextserialport-1.2beta2/lib/ -lqextserialport-1.2 -lQtSql -L/usr/local/Qt.4.7-static/lib -lQtOpenGL -L/usr/X11R6/lib -lQtGui -lpng -lgobject-2.0 -lSM -lICE -lXrender -lfontconfig -lfreetype -lXext -lX11 -lQtNetwork -lQtCore -lz -lm -ldl -pthread -lgthread-2.0 -lrt -lglib-2.0 -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Qt.4.7-static/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		param_vibrasi.cpp \
		create_sinus.cpp \
		libku/fft/fourierf.c \
		libku/fft/fftmisc.c \
		libku/libmodbus/src/modbus.c \
		libku/libmodbus/src/modbus-data.c \
		libku/libmodbus/src/modbus-rtu.c \
		libku/dsp/integrasi.c \
		libku/windowing/windowkan.c \
		libku/windowing/buat_filter.c \
		simpanthread.cpp \
		libku/dsp/itung_rms.c \
		kanalview.cpp \
		waterfall.cpp \
		spektrum.cpp \
		waveform.cpp \
		signalgeneratorset.cpp \
		modulsetting.cpp \
		dbcontrol.cpp \
		motorcontrol.cpp \
		versusview.cpp \
		waveformvs.cpp \
		polar.cpp \
		libku/dsp/filter_lib.c moc_mainwindow.cpp \
		moc_simpanthread.cpp \
		moc_kanalview.cpp \
		moc_spektrum.cpp \
		moc_signalgeneratorset.cpp \
		moc_modulsetting.cpp \
		moc_dbcontrol.cpp \
		moc_motorcontrol.cpp \
		moc_versusview.cpp
OBJECTS       = main.o \
		mainwindow.o \
		param_vibrasi.o \
		create_sinus.o \
		fourierf.o \
		fftmisc.o \
		modbus.o \
		modbus-data.o \
		modbus-rtu.o \
		integrasi.o \
		windowkan.o \
		buat_filter.o \
		simpanthread.o \
		itung_rms.o \
		kanalview.o \
		waterfall.o \
		spektrum.o \
		waveform.o \
		signalgeneratorset.o \
		modulsetting.o \
		dbcontrol.o \
		motorcontrol.o \
		versusview.o \
		waveformvs.o \
		polar.o \
		filter_lib.o \
		moc_mainwindow.o \
		moc_simpanthread.o \
		moc_kanalview.o \
		moc_spektrum.o \
		moc_signalgeneratorset.o \
		moc_modulsetting.o \
		moc_dbcontrol.o \
		moc_motorcontrol.o \
		moc_versusview.o
DIST          = /usr/local/Qt.4.7-static/mkspecs/common/g++.conf \
		/usr/local/Qt.4.7-static/mkspecs/common/unix.conf \
		/usr/local/Qt.4.7-static/mkspecs/common/linux.conf \
		/usr/local/Qt.4.7-static/mkspecs/qconfig.pri \
		/usr/local/Qt.4.7-static/mkspecs/features/qt_functions.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/qt_config.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/default_pre.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/debug.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/default_post.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/static.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/staticlib.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/warn_on.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/qt.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/unix/thread.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/moc.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/resources.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/uic.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/yacc.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/lex.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/include_source_dir.prf \
		qt_simul.pro
QMAKE_TARGET  = qt_simul
DESTDIR       = 
TARGET        = qt_simul

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/iqbal/suralaya/master/libku/qextserialport-1.2beta2/lib/libqextserialport-1.2.a ui_mainwindow.h ui_kanalview.h ui_signalgeneratorset.h ui_modulsetting.h ui_dbcontrol.h ui_motorcontrol.h ui_versusview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt_simul.pro  /usr/local/Qt.4.7-static/mkspecs/linux-g++/qmake.conf /usr/local/Qt.4.7-static/mkspecs/common/g++.conf \
		/usr/local/Qt.4.7-static/mkspecs/common/unix.conf \
		/usr/local/Qt.4.7-static/mkspecs/common/linux.conf \
		/usr/local/Qt.4.7-static/mkspecs/qconfig.pri \
		/usr/local/Qt.4.7-static/mkspecs/features/qt_functions.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/qt_config.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/default_pre.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/debug.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/default_post.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/static.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/staticlib.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/warn_on.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/qt.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/unix/thread.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/moc.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/resources.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/uic.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/yacc.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/lex.prf \
		/usr/local/Qt.4.7-static/mkspecs/features/include_source_dir.prf \
		/usr/local/Qt.4.7-static/lib/libQtSql.prl \
		/usr/local/Qt.4.7-static/lib/libQtCore.prl \
		/usr/local/Qt.4.7-static/lib/libQtOpenGL.prl \
		/usr/local/Qt.4.7-static/lib/libQtGui.prl \
		/usr/local/Qt.4.7-static/lib/libQtNetwork.prl
	$(QMAKE) -spec /usr/local/Qt.4.7-static/mkspecs/linux-g++ CONFIG+=debug -o Makefile qt_simul.pro
/usr/local/Qt.4.7-static/mkspecs/common/g++.conf:
/usr/local/Qt.4.7-static/mkspecs/common/unix.conf:
/usr/local/Qt.4.7-static/mkspecs/common/linux.conf:
/usr/local/Qt.4.7-static/mkspecs/qconfig.pri:
/usr/local/Qt.4.7-static/mkspecs/features/qt_functions.prf:
/usr/local/Qt.4.7-static/mkspecs/features/qt_config.prf:
/usr/local/Qt.4.7-static/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt.4.7-static/mkspecs/features/default_pre.prf:
/usr/local/Qt.4.7-static/mkspecs/features/debug.prf:
/usr/local/Qt.4.7-static/mkspecs/features/default_post.prf:
/usr/local/Qt.4.7-static/mkspecs/features/static.prf:
/usr/local/Qt.4.7-static/mkspecs/features/staticlib.prf:
/usr/local/Qt.4.7-static/mkspecs/features/warn_on.prf:
/usr/local/Qt.4.7-static/mkspecs/features/qt.prf:
/usr/local/Qt.4.7-static/mkspecs/features/unix/opengl.prf:
/usr/local/Qt.4.7-static/mkspecs/features/unix/thread.prf:
/usr/local/Qt.4.7-static/mkspecs/features/moc.prf:
/usr/local/Qt.4.7-static/mkspecs/features/resources.prf:
/usr/local/Qt.4.7-static/mkspecs/features/uic.prf:
/usr/local/Qt.4.7-static/mkspecs/features/yacc.prf:
/usr/local/Qt.4.7-static/mkspecs/features/lex.prf:
/usr/local/Qt.4.7-static/mkspecs/features/include_source_dir.prf:
/usr/local/Qt.4.7-static/lib/libQtSql.prl:
/usr/local/Qt.4.7-static/lib/libQtCore.prl:
/usr/local/Qt.4.7-static/lib/libQtOpenGL.prl:
/usr/local/Qt.4.7-static/lib/libQtGui.prl:
/usr/local/Qt.4.7-static/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt.4.7-static/mkspecs/linux-g++ CONFIG+=debug -o Makefile qt_simul.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qt_simul1.0.0 || $(MKDIR) .tmp/qt_simul1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qt_simul1.0.0/ && $(COPY_FILE) --parents mainwindow.h lain.h create_sinus.h libku/libmodbus/src/modbus.h libku/libmodbus/config.h libku/dsp/integrasi.h simpanthread.h mainwindow.h libku/windowing/buat_filter.h libku/windowing/windowkan.h kanalview.h waterfall.h spektrum.h waveform.h alokasi.h signalgeneratorset.h modulsetting.h dbcontrol.h motorcontrol.h libku/dsp/itung_rms.h libku/dsp/integrasi.h versusview.h waveformvs.h polar.h libku/dsp/filter_lib.h libku/dsp/rute.h .tmp/qt_simul1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp param_vibrasi.cpp create_sinus.cpp libku/fft/fourierf.c libku/fft/fftmisc.c libku/libmodbus/src/modbus.c libku/libmodbus/src/modbus-data.c libku/libmodbus/src/modbus-rtu.c libku/dsp/integrasi.c libku/windowing/windowkan.c libku/windowing/buat_filter.c simpanthread.cpp libku/dsp/itung_rms.c kanalview.cpp waterfall.cpp spektrum.cpp waveform.cpp signalgeneratorset.cpp modulsetting.cpp dbcontrol.cpp motorcontrol.cpp versusview.cpp waveformvs.cpp polar.cpp libku/dsp/filter_lib.c .tmp/qt_simul1.0.0/ && $(COPY_FILE) --parents mainwindow.ui kanalview.ui signalgeneratorset.ui modulsetting.ui dbcontrol.ui motorcontrol.ui versusview.ui .tmp/qt_simul1.0.0/ && (cd `dirname .tmp/qt_simul1.0.0` && $(TAR) qt_simul1.0.0.tar qt_simul1.0.0 && $(COMPRESS) qt_simul1.0.0.tar) && $(MOVE) `dirname .tmp/qt_simul1.0.0`/qt_simul1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qt_simul1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_simpanthread.cpp moc_mainwindow.cpp moc_kanalview.cpp moc_spektrum.cpp moc_signalgeneratorset.cpp moc_modulsetting.cpp moc_dbcontrol.cpp moc_motorcontrol.cpp moc_versusview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_simpanthread.cpp moc_mainwindow.cpp moc_kanalview.cpp moc_spektrum.cpp moc_signalgeneratorset.cpp moc_modulsetting.cpp moc_dbcontrol.cpp moc_motorcontrol.cpp moc_versusview.cpp
moc_mainwindow.cpp: lain.h \
		modulsetting.h \
		signalgeneratorset.h \
		dbcontrol.h \
		simpanthread.h \
		alokasi.h \
		motorcontrol.h \
		libku/qextserialport-1.2beta2/src/qextserialenumerator.h \
		libku/qextserialport-1.2beta2/src/qextserialport_global.h \
		libku/fft/fourier.h \
		libku/dsp/integrasi.h \
		kanalview.h \
		waveform.h \
		libku/dsp/itung_rms.h \
		polar.h \
		spektrum.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		waterfall.h \
		libku/dsp/window_filter.h \
		libku/dsp/rute.h \
		versusview.h \
		waveformvs.h \
		mainwindow.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_simpanthread.cpp: simpanthread.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) simpanthread.h -o moc_simpanthread.cpp

moc_mainwindow.cpp: lain.h \
		modulsetting.h \
		signalgeneratorset.h \
		dbcontrol.h \
		simpanthread.h \
		alokasi.h \
		motorcontrol.h \
		libku/qextserialport-1.2beta2/src/qextserialenumerator.h \
		libku/qextserialport-1.2beta2/src/qextserialport_global.h \
		libku/fft/fourier.h \
		libku/dsp/integrasi.h \
		kanalview.h \
		waveform.h \
		libku/dsp/itung_rms.h \
		polar.h \
		spektrum.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		waterfall.h \
		libku/dsp/window_filter.h \
		libku/dsp/rute.h \
		versusview.h \
		waveformvs.h \
		mainwindow.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_kanalview.cpp: waveform.h \
		alokasi.h \
		libku/dsp/itung_rms.h \
		lain.h \
		polar.h \
		spektrum.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		libku/fft/fourier.h \
		waterfall.h \
		libku/dsp/integrasi.h \
		libku/dsp/window_filter.h \
		libku/dsp/rute.h \
		kanalview.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) kanalview.h -o moc_kanalview.cpp

moc_spektrum.cpp: alokasi.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		libku/fft/fourier.h \
		lain.h \
		spektrum.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) spektrum.h -o moc_spektrum.cpp

moc_signalgeneratorset.cpp: lain.h \
		signalgeneratorset.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) signalgeneratorset.h -o moc_signalgeneratorset.cpp

moc_modulsetting.cpp: lain.h \
		modulsetting.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) modulsetting.h -o moc_modulsetting.cpp

moc_dbcontrol.cpp: lain.h \
		simpanthread.h \
		alokasi.h \
		dbcontrol.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) dbcontrol.h -o moc_dbcontrol.cpp

moc_motorcontrol.cpp: libku/qextserialport-1.2beta2/src/qextserialenumerator.h \
		libku/qextserialport-1.2beta2/src/qextserialport_global.h \
		lain.h \
		motorcontrol.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) motorcontrol.h -o moc_motorcontrol.cpp

moc_versusview.cpp: waveformvs.h \
		alokasi.h \
		libku/dsp/itung_rms.h \
		lain.h \
		libku/dsp/integrasi.h \
		libku/dsp/window_filter.h \
		versusview.h
	/usr/local/Qt.4.7-static/bin/moc $(DEFINES) $(INCPATH) versusview.h -o moc_versusview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_kanalview.h ui_signalgeneratorset.h ui_modulsetting.h ui_dbcontrol.h ui_motorcontrol.h ui_versusview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_kanalview.h ui_signalgeneratorset.h ui_modulsetting.h ui_dbcontrol.h ui_motorcontrol.h ui_versusview.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Qt.4.7-static/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_kanalview.h: kanalview.ui
	/usr/local/Qt.4.7-static/bin/uic kanalview.ui -o ui_kanalview.h

ui_signalgeneratorset.h: signalgeneratorset.ui
	/usr/local/Qt.4.7-static/bin/uic signalgeneratorset.ui -o ui_signalgeneratorset.h

ui_modulsetting.h: modulsetting.ui
	/usr/local/Qt.4.7-static/bin/uic modulsetting.ui -o ui_modulsetting.h

ui_dbcontrol.h: dbcontrol.ui
	/usr/local/Qt.4.7-static/bin/uic dbcontrol.ui -o ui_dbcontrol.h

ui_motorcontrol.h: motorcontrol.ui
	/usr/local/Qt.4.7-static/bin/uic motorcontrol.ui -o ui_motorcontrol.h

ui_versusview.h: versusview.ui
	/usr/local/Qt.4.7-static/bin/uic versusview.ui -o ui_versusview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		lain.h \
		modulsetting.h \
		signalgeneratorset.h \
		dbcontrol.h \
		simpanthread.h \
		alokasi.h \
		motorcontrol.h \
		libku/qextserialport-1.2beta2/src/qextserialenumerator.h \
		libku/qextserialport-1.2beta2/src/qextserialport_global.h \
		libku/fft/fourier.h \
		libku/dsp/integrasi.h \
		kanalview.h \
		waveform.h \
		libku/dsp/itung_rms.h \
		polar.h \
		spektrum.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		waterfall.h \
		libku/dsp/window_filter.h \
		libku/dsp/rute.h \
		versusview.h \
		waveformvs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		lain.h \
		modulsetting.h \
		signalgeneratorset.h \
		dbcontrol.h \
		simpanthread.h \
		alokasi.h \
		motorcontrol.h \
		libku/qextserialport-1.2beta2/src/qextserialenumerator.h \
		libku/qextserialport-1.2beta2/src/qextserialport_global.h \
		libku/fft/fourier.h \
		libku/dsp/integrasi.h \
		kanalview.h \
		waveform.h \
		libku/dsp/itung_rms.h \
		polar.h \
		spektrum.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		waterfall.h \
		libku/dsp/window_filter.h \
		libku/dsp/rute.h \
		versusview.h \
		waveformvs.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

param_vibrasi.o: param_vibrasi.cpp lain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o param_vibrasi.o param_vibrasi.cpp

create_sinus.o: create_sinus.cpp create_sinus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o create_sinus.o create_sinus.cpp

fourierf.o: libku/fft/fourierf.c libku/fft/fourier.h \
		libku/fft/ddcmath.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fourierf.o libku/fft/fourierf.c

fftmisc.o: libku/fft/fftmisc.c libku/fft/fourier.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o fftmisc.o libku/fft/fftmisc.c

modbus.o: libku/libmodbus/src/modbus.c libku/libmodbus/src/modbus.h \
		libku/libmodbus/src/modbus-version.h \
		libku/libmodbus/src/modbus-tcp.h \
		libku/libmodbus/src/modbus-rtu.h \
		libku/libmodbus/src/modbus-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus.o libku/libmodbus/src/modbus.c

modbus-data.o: libku/libmodbus/src/modbus-data.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-data.o libku/libmodbus/src/modbus-data.c

modbus-rtu.o: libku/libmodbus/src/modbus-rtu.c libku/libmodbus/src/modbus-private.h \
		libku/libmodbus/src/modbus.h \
		libku/libmodbus/src/modbus-version.h \
		libku/libmodbus/src/modbus-tcp.h \
		libku/libmodbus/src/modbus-rtu.h \
		libku/libmodbus/src/modbus-rtu-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-rtu.o libku/libmodbus/src/modbus-rtu.c

integrasi.o: libku/dsp/integrasi.c libku/dsp/integrasi.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o integrasi.o libku/dsp/integrasi.c

windowkan.o: libku/windowing/windowkan.c libku/windowing/windowkan.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o windowkan.o libku/windowing/windowkan.c

buat_filter.o: libku/windowing/buat_filter.c libku/windowing/buat_filter.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o buat_filter.o libku/windowing/buat_filter.c

simpanthread.o: simpanthread.cpp simpanthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simpanthread.o simpanthread.cpp

itung_rms.o: libku/dsp/itung_rms.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o itung_rms.o libku/dsp/itung_rms.c

kanalview.o: kanalview.cpp kanalview.h \
		waveform.h \
		alokasi.h \
		libku/dsp/itung_rms.h \
		lain.h \
		polar.h \
		spektrum.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		libku/fft/fourier.h \
		waterfall.h \
		libku/dsp/integrasi.h \
		libku/dsp/window_filter.h \
		libku/dsp/rute.h \
		ui_kanalview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kanalview.o kanalview.cpp

waterfall.o: waterfall.cpp waterfall.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		libku/fft/fourier.h \
		alokasi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waterfall.o waterfall.cpp

spektrum.o: spektrum.cpp spektrum.h \
		alokasi.h \
		libku/windowing/windowkan.h \
		libku/windowing/buat_filter.h \
		libku/fft/fourier.h \
		lain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spektrum.o spektrum.cpp

waveform.o: waveform.cpp waveform.h \
		alokasi.h \
		libku/dsp/itung_rms.h \
		lain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waveform.o waveform.cpp

signalgeneratorset.o: signalgeneratorset.cpp signalgeneratorset.h \
		lain.h \
		ui_signalgeneratorset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalgeneratorset.o signalgeneratorset.cpp

modulsetting.o: modulsetting.cpp modulsetting.h \
		lain.h \
		ui_modulsetting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modulsetting.o modulsetting.cpp

dbcontrol.o: dbcontrol.cpp dbcontrol.h \
		lain.h \
		simpanthread.h \
		alokasi.h \
		ui_dbcontrol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbcontrol.o dbcontrol.cpp

motorcontrol.o: motorcontrol.cpp motorcontrol.h \
		libku/qextserialport-1.2beta2/src/qextserialenumerator.h \
		libku/qextserialport-1.2beta2/src/qextserialport_global.h \
		lain.h \
		ui_motorcontrol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o motorcontrol.o motorcontrol.cpp

versusview.o: versusview.cpp versusview.h \
		waveformvs.h \
		alokasi.h \
		libku/dsp/itung_rms.h \
		lain.h \
		libku/dsp/integrasi.h \
		libku/dsp/window_filter.h \
		ui_versusview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o versusview.o versusview.cpp

waveformvs.o: waveformvs.cpp waveformvs.h \
		alokasi.h \
		libku/dsp/itung_rms.h \
		lain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waveformvs.o waveformvs.cpp

polar.o: polar.cpp polar.h \
		alokasi.h \
		libku/dsp/itung_rms.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o polar.o polar.cpp

filter_lib.o: libku/dsp/filter_lib.c libku/dsp/filter_lib.h \
		libku/dsp/window_filter.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o filter_lib.o libku/dsp/filter_lib.c

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_simpanthread.o: moc_simpanthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_simpanthread.o moc_simpanthread.cpp

moc_kanalview.o: moc_kanalview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kanalview.o moc_kanalview.cpp

moc_spektrum.o: moc_spektrum.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spektrum.o moc_spektrum.cpp

moc_signalgeneratorset.o: moc_signalgeneratorset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_signalgeneratorset.o moc_signalgeneratorset.cpp

moc_modulsetting.o: moc_modulsetting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modulsetting.o moc_modulsetting.cpp

moc_dbcontrol.o: moc_dbcontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbcontrol.o moc_dbcontrol.cpp

moc_motorcontrol.o: moc_motorcontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_motorcontrol.o moc_motorcontrol.cpp

moc_versusview.o: moc_versusview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_versusview.o moc_versusview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

